import warnings
import time
import torch
import torch.nn as nn
from typing import Optional, Callable, Union, Any, List, Tuple, Dict, Literal
from .....models.utils import MLTransform, MLModule
import numpy as np
from torch.func import vmap
import joblib

__all__ = [
    "ColumnTransformer",
    "KNeighborsTransformer",
    "RadiusNeighborsTransformer",
    "RandomTreesEmbeddings",
    "FeatureUnion",
]


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

def _to_tensor(X: Any, dtype: torch.dtype, device: torch.device) -> torch.Tensor:
    """Convert array-like / DataFrame / Tensor to a 2-D float Tensor."""
    try:
        import pandas as pd  # pyright: ignore[reportMissingImports]
        if isinstance(X, pd.DataFrame):
            return torch.tensor(X.values, dtype=dtype, device=device)
        if isinstance(X, pd.Series):
            return torch.tensor(X.values, dtype=dtype, device=device).unsqueeze(1)
    except ImportError:
        pass
    if isinstance(X, torch.Tensor):
        return X.to(dtype=dtype, device=device)
    return torch.tensor(np.array(X), dtype=dtype, device=device)


def _get_feature_names(X: Any) -> Optional[List[str]]:
    """Return column names if X is a DataFrame, else None."""
    try:
        import pandas as pd  # pyright: ignore[reportMissingImports]
        if isinstance(X, pd.DataFrame):
            return list(X.columns)
    except ImportError:
        pass
    return None


def _resolve_columns(X_t: torch.Tensor, columns: Any,
                     feature_names: Optional[List[str]]) -> List[int]:
    """
    Resolve a column specification to a list of integer indices.

    Supports: int, str, slice, list/tuple of int/str/bool,
    bool Tensor/array, callable.
    """
    n_cols = X_t.shape[1]

    if callable(columns):
        columns = columns(X_t)

    if isinstance(columns, slice):
        return list(range(*columns.indices(n_cols)))

    if isinstance(columns, int):
        return [columns]

    if isinstance(columns, str):
        if feature_names is None:
            raise ValueError("String column selector requires a DataFrame input.")
        return [feature_names.index(columns)]

    if isinstance(columns, torch.Tensor):
        if columns.dtype == torch.bool:
            return columns.nonzero(as_tuple=True)[0].tolist()
        return columns.long().tolist()

    if isinstance(columns, (list, tuple, np.ndarray)):
        arr = list(columns)
        if len(arr) == 0:
            return []
        first = arr[0]
        if isinstance(first, bool) or (isinstance(first, (int, np.integer))
                                       and all(isinstance(v, (bool, np.bool_)) for v in arr)):
            return [i for i, v in enumerate(arr) if v]
        result: List[int] = []
        for c in arr:
            if isinstance(c, (bool, np.bool_)):
                # boolean array – rebuild
                return [i for i, v in enumerate(arr) if v]
            elif isinstance(c, str):
                if feature_names is None:
                    raise ValueError(
                        "String column selectors require a DataFrame input.")
                result.append(feature_names.index(c))
            else:
                result.append(int(c))
        return result

    raise ValueError(f"Cannot interpret columns={columns!r}.")


def _make_generator(random_state: Union[int, torch.Generator, None],
                    device: torch.device) -> torch.Generator:
    gen = torch.Generator(device=device)
    if isinstance(random_state, torch.Generator):
        return random_state
    if isinstance(random_state, int):
        gen.manual_seed(random_state)
    else:
        gen.seed()
    return gen


# ---------------------------------------------------------------------------
# ColumnTransformer
# ---------------------------------------------------------------------------

class ColumnTransformer(MLTransform):
    """
    Applies transformers to columns of an array or pandas DataFrame.

    This estimator allows different columns or column subsets of the input
    to be transformed separately and the features generated by each transformer
    will be concatenated to form a single feature space.
    This is useful for heterogeneous or columnar data, to combine several
    feature extraction mechanisms or transformations into a single transformer.

    Read more in the :ref:`User Guide <column_transformer>`.

    .. versionadded:: 0.20

    Parameters
    ----------
    transformers : list of tuples
        List of (name, transformer, columns) tuples specifying the
        transformer objects to be applied to subsets of the data.

        name : str
            Like in Pipeline and FeatureUnion, this allows the transformer and
            its parameters to be set using ``set_params`` and searched in grid
            search.
        transformer : {'drop', 'passthrough'} or estimator
            Estimator must support :term:`fit` and :term:`transform`.
            Special-cased strings 'drop' and 'passthrough' are accepted as
            well, to indicate to drop the columns or to pass them through
            untransformed, respectively.
        columns :  str, array-like of str, int, array-like of int, \
                array-like of bool, slice or callable
            Indexes the data on its second axis. Integers are interpreted as
            positional columns, while strings can reference DataFrame columns
            by name.  A scalar string or int should be used where
            ``transformer`` expects X to be a 1d array-like (vector),
            otherwise a 2d array will be passed to the transformer.
            A callable is passed the input data `X` and can return any of the
            above. To select multiple columns by name or dtype, you can use
            :obj:`make_column_selector`.

    remainder : {'drop', 'passthrough'} or estimator, default='drop'
        By default, only the specified columns in `transformers` are
        transformed and combined in the output, and the non-specified
        columns are dropped. (default of ``'drop'``).
        By specifying ``remainder='passthrough'``, all remaining columns that
        were not specified in `transformers`, but present in the data passed
        to `fit` will be automatically passed through. This subset of columns
        is concatenated with the output of the transformers. For dataframes,
        extra columns not seen during `fit` will be excluded from the output
        of `transform`.
        By setting ``remainder`` to be an estimator, the remaining
        non-specified columns will use the ``remainder`` estimator. The
        estimator must support :term:`fit` and :term:`transform`.
        Note that using this feature requires that the DataFrame columns
        input at :term:`fit` and :term:`transform` have identical order.

    sparse_threshold : float, default=0.3
        If the output of the different transformers contains sparse matrices,
        these will be stacked as a sparse matrix if the overall density is
        lower than this value. Use ``sparse_threshold=0`` to always return
        dense.  When the transformed output consists of all dense data, the
        stacked result will be dense, and this keyword will be ignored.

    n_jobs : int, default=None
        Number of jobs to run in parallel.
        ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
        ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
        for more details.

    transformer_weights : dict, default=None
        Multiplicative weights for features per transformer. The output of the
        transformer is multiplied by these weights. Keys are transformer names,
        values the weights.

    verbose : bool, default=False
        If True, the time elapsed while fitting each transformer will be
        printed as it is completed.

    verbose_feature_names_out : bool, str or Callable[[str, str], str], default=True

        - If True, :meth:`ColumnTransformer.get_feature_names_out` will prefix
          all feature names with the name of the transformer that generated that
          feature. It is equivalent to setting
          `verbose_feature_names_out="{transformer_name}__{feature_name}"`.
        - If False, :meth:`ColumnTransformer.get_feature_names_out` will not
          prefix any feature names and will error if feature names are not
          unique.
        - If ``Callable[[str, str], str]``,
          :meth:`ColumnTransformer.get_feature_names_out` will rename all the features
          using the name of the transformer. The first argument of the callable is the
          transformer name and the second argument is the feature name. The returned
          string will be the new feature name.
        - If ``str``, it must be a string ready for formatting. The given string will
          be formatted using two field names: ``transformer_name`` and ``feature_name``.
          e.g. ``"{feature_name}__{transformer_name}"``. See :meth:`str.format` method
          from the standard library for more info.

        .. versionadded:: 1.0

        .. versionchanged:: 1.6
            `verbose_feature_names_out` can be a callable or a string to be formatted.

    force_int_remainder_cols : bool, default=False
        This parameter has no effect.

        .. note::
            If you do not access the list of columns for the remainder columns
            in the `transformers_` fitted attribute, you do not need to set
            this parameter.

        .. versionadded:: 1.5

        .. versionchanged:: 1.7
           The default value for `force_int_remainder_cols` will change from
           `True` to `False` in version 1.7.

        .. deprecated:: 1.7
           `force_int_remainder_cols` is deprecated and will be removed in 1.9.

    Attributes
    ----------
    transformers_ : list
        The collection of fitted transformers as tuples of (name,
        fitted_transformer, column). `fitted_transformer` can be an estimator,
        or `'drop'`; `'passthrough'` is replaced with an equivalent
        :class:`~sklearn.preprocessing.FunctionTransformer`. In case there were
        no columns selected, this will be the unfitted transformer. If there
        are remaining columns, the final element is a tuple of the form:
        ('remainder', transformer, remaining_columns) corresponding to the
        ``remainder`` parameter. If there are remaining columns, then
        ``len(transformers_)==len(transformers)+1``, otherwise
        ``len(transformers_)==len(transformers)``.

        .. versionadded:: 1.7
            The format of the remaining columns now attempts to match that of the other
            transformers: if all columns were provided as column names (`str`), the
            remaining columns are stored as column names; if all columns were provided
            as mask arrays (`bool`), so are the remaining columns; in all other cases
            the remaining columns are stored as indices (`int`).

    named_transformers_ : :class:`~sklearn.utils.Bunch`
        Read-only attribute to access any transformer by given name.
        Keys are transformer names and values are the fitted transformer
        objects.

    sparse_output_ : bool
        Boolean flag indicating whether the output of ``transform`` is a
        sparse matrix or a dense numpy array, which depends on the output
        of the individual transformers and the `sparse_threshold` keyword.

    output_indices_ : dict
        A dictionary from each transformer name to a slice, where the slice
        corresponds to indices in the transformed output. This is useful to
        inspect which transformer is responsible for which transformed
        feature(s).

        .. versionadded:: 1.0

    n_features_in_ : int
        Number of features seen during :term:`fit`. Only defined if the
        underlying transformers expose such an attribute when fit.
    """
    def __init__(self,
                 transformers: Union[List[Union[list, tuple]],
                    Tuple[List[Union[list, tuple]]],
                    torch.Tensor,
                    None] = None,
                 name: str = None,
                 transformer: Union[Literal["drop", "passthrough"], MLModule] = None,
                 columns: Union[str, int, slice, List[Union[str, int, bool]],
                    Tuple[Union[str, int, bool]], torch.Tensor, Callable, nn.Module] = None,
                 remainder: Union[Literal["drop", "passthrough"], MLModule] = "drop",
                 sparse_threshold: float = 0.3,
                 n_jobs: int = None,
                 transformer_weights: dict = None,
                 verbose: bool = False,
                 verbose_feature_names_out: Union[bool, str, Callable[[str, str], str]] = True,
                 device: Union[str, torch.device] = "cpu",
                 dtype: torch.dtype = torch.float,
                 *args,
                 **kwargs,
                 ):
        super().__init__()
        # If a single (name, transformer, columns) triple is provided as separate
        # args, merge it into the transformers list.
        self.transformers = list(transformers) if transformers is not None else []
        if name is not None and transformer is not None and columns is not None:
            self.transformers.append((name, transformer, columns))

        self.name = name
        self.transformer = transformer
        self.columns = columns
        self.remainder = remainder
        self.sparse_threshold = sparse_threshold
        self.n_jobs = n_jobs
        self.transformer_weights = transformer_weights or {}
        self.verbose = verbose
        self.verbose_feature_names_out = verbose_feature_names_out
        self.device = (torch.device(device)
                       if isinstance(device, str) else device)
        self.dtype = dtype
        self.args = args
        self.kwargs = kwargs

        # Fitted attributes
        self.transformers_: List[Tuple] = []
        self.named_transformers_: Dict[str, Any] = {}
        self.sparse_output_: bool = False
        self.output_indices_: Dict[str, slice] = {}
        self.n_features_in_: Optional[int] = None
        self.fit_status = False

    # ------------------------------------------------------------------
    def _get_transformer_in(self, t_name: str, t: Any, col_idx: List[int],
                            X_t: torch.Tensor) -> torch.Tensor:
        """Extract the column slice for a single transformer."""
        sub = X_t[:, col_idx]
        # Scalar column: keep 2-D
        return sub

    def _fit_one(self, t_name: str, t: Any, col_idx: List[int],
                 X_t: torch.Tensor, y: Any = None):
        """Fit a single transformer and return the fitted object."""
        if t == "drop":
            return "drop"
        sub = self._get_transformer_in(t_name, t, col_idx, X_t)
        if t == "passthrough":
            return "passthrough"
        t0 = time.time() if self.verbose else None
        t.fit(sub, y)
        if self.verbose:
            print(f"[ColumnTransformer] Fitting {t_name!r} done in "
                  f"{time.time() - t0:.3f}s")
        return t

    def _transform_one(self, t_name: str, t: Any, col_idx: List[int],
                       X_t: torch.Tensor) -> Optional[torch.Tensor]:
        """Transform X using a single fitted transformer."""
        if t == "drop":
            return None
        sub = self._get_transformer_in(t_name, t, col_idx, X_t)
        if t == "passthrough":
            return sub
        result = t.transform(sub)
        if isinstance(result, torch.Tensor) and result.is_sparse:
            result = result.to_dense()
        result = result.to(dtype=self.dtype, device=self.device)
        # Apply weight
        w = self.transformer_weights.get(t_name)
        if w is not None:
            result = result * w
        return result

    # ------------------------------------------------------------------
    def fit(self, X: Any, y: Any = None, **kwargs) -> "ColumnTransformer":
        feature_names = _get_feature_names(X)
        X_t = _to_tensor(X, self.dtype, self.device)
        if X_t.ndim == 1:
            X_t = X_t.unsqueeze(1)
        n_samples, n_cols = X_t.shape
        self.n_features_in_ = n_cols

        # Collect all specified column indices
        all_specified: set = set()
        self.transformers_ = []
        self.named_transformers_ = {}

        for entry in self.transformers:
            t_name, t, cols = entry[0], entry[1], entry[2]
            col_idx = _resolve_columns(X_t, cols, feature_names)
            all_specified.update(col_idx)
            fitted_t = self._fit_one(t_name, t, col_idx, X_t, y)
            self.transformers_.append((t_name, fitted_t, col_idx))
            self.named_transformers_[t_name] = fitted_t

        # Handle remainder columns
        remainder_cols = [i for i in range(n_cols) if i not in all_specified]
        if remainder_cols:
            rem = self.remainder
            if rem == "drop":
                fitted_rem = "drop"
            elif rem == "passthrough":
                fitted_rem = "passthrough"
            else:
                # estimator
                fitted_rem = self._fit_one("remainder", rem, remainder_cols, X_t, y)
            self.transformers_.append(("remainder", fitted_rem, remainder_cols))
            self.named_transformers_["remainder"] = fitted_rem

        self.fit_status = True
        return self

    # ------------------------------------------------------------------
    def transform(self, X: Any, **kwargs) -> torch.Tensor:
        if not self.fit_status:
            raise RuntimeError("Call fit() before transform().")
        feature_names = _get_feature_names(X)
        X_t = _to_tensor(X, self.dtype, self.device)
        if X_t.ndim == 1:
            X_t = X_t.unsqueeze(1)

        parts: List[torch.Tensor] = []
        col_offset = 0
        self.output_indices_ = {}

        for t_name, t, col_idx in self.transformers_:
            result = self._transform_one(t_name, t, col_idx, X_t)
            if result is None:
                continue
            if result.ndim == 1:
                result = result.unsqueeze(1)
            n_out = result.shape[1]
            self.output_indices_[t_name] = slice(col_offset, col_offset + n_out)
            col_offset += n_out
            parts.append(result)

        if not parts:
            return torch.zeros(X_t.shape[0], 0,
                               dtype=self.dtype, device=self.device)

        out = torch.cat(parts, dim=1)

        # Determine sparse_output_
        density = out.count_nonzero().item() / max(out.numel(), 1)
        self.sparse_output_ = density < self.sparse_threshold
        if self.sparse_output_:
            return out.to_sparse()
        return out

    # ------------------------------------------------------------------
    def fit_transform(self, X: Any, y: Any = None, **kwargs) -> torch.Tensor:
        return self.fit(X, y, **kwargs).transform(X, **kwargs)

    # ------------------------------------------------------------------
    def get_feature_names_out(
        self, input_features: Optional[List[str]] = None
    ) -> List[str]:
        if not self.fit_status:
            raise RuntimeError("Call fit() before get_feature_names_out().")

        vfno = self.verbose_feature_names_out
        out_names: List[str] = []

        for t_name, t, col_idx in self.transformers_:
            if t == "drop":
                continue
            if t == "passthrough":
                sub_names = ([input_features[i] for i in col_idx]
                             if input_features else [f"x{i}" for i in col_idx])
            elif hasattr(t, "get_feature_names_out"):
                sub_names = list(t.get_feature_names_out())
            else:
                sub_names = [f"x{i}" for i in col_idx]

            for fn in sub_names:
                if vfno is True:
                    out_names.append(f"{t_name}__{fn}")
                elif vfno is False:
                    out_names.append(fn)
                elif isinstance(vfno, str):
                    out_names.append(
                        vfno.format(transformer_name=t_name, feature_name=fn))
                elif callable(vfno):
                    out_names.append(vfno(t_name, fn))
                else:
                    out_names.append(fn)

        return out_names

    # ------------------------------------------------------------------
    def forward(self, X: Any, **kwargs) -> torch.Tensor:
        if not self.fit_status:
            self.fit(X, **kwargs)
        return self.transform(X, **kwargs)

    # ------------------------------------------------------------------
    def predict(self, X: Any, **kwargs) -> torch.Tensor:
        return self.transform(X, **kwargs)

    # ------------------------------------------------------------------
    def score(self, X: Any, y: Any = None, **kwargs) -> float:
        return 0.0


# ---------------------------------------------------------------------------
# KNeighborsTransformer
# ---------------------------------------------------------------------------

class KNeighborsTransformer(MLTransform):
    """
    Transform X into a (weighted) graph of k nearest neighbors.

    The transformed data is a sparse graph as returned by kneighbors_graph.

    Read more in the :ref:`User Guide <neighbors_transformer>`.

    .. versionadded:: 0.22

    Parameters
    ----------
    mode : {'distance', 'connectivity'}, default='distance'
        Type of returned matrix: 'connectivity' will return the connectivity
        matrix with ones and zeros, and 'distance' will return the distances
        between neighbors according to the given metric.

    n_neighbors : int, default=5
        Number of neighbors for each sample in the transformed sparse graph.
        For compatibility reasons, as each sample is considered as its own
        neighbor, one extra neighbor will be computed when mode == 'distance'.
        In this case, the sparse graph contains (n_neighbors + 1) neighbors.

    algorithm : {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'
        Algorithm used to compute the nearest neighbors:

        - 'ball_tree' will use :class:`BallTree`
        - 'kd_tree' will use :class:`KDTree`
        - 'brute' will use a brute-force search.
        - 'auto' will attempt to decide the most appropriate algorithm
          based on the values passed to :meth:`fit` method.

        Note: fitting on sparse input will override the setting of
        this parameter, using brute force.

    leaf_size : int, default=30
        Leaf size passed to BallTree or KDTree.  This can affect the
        speed of the construction and query, as well as the memory
        required to store the tree.  The optimal value depends on the
        nature of the problem.

    metric : str or callable, default='minkowski'
        Metric to use for distance computation. Default is "minkowski", which
        results in the standard Euclidean distance when p = 2. See the
        documentation of `scipy.spatial.distance
        <https://docs.scipy.org/doc/scipy/reference/spatial.distance.html>`_ and
        the metrics listed in
        :class:`~sklearn.metrics.pairwise.distance_metrics` for valid metric
        values.

        If metric is a callable function, it takes two arrays representing 1D
        vectors as inputs and must return one value indicating the distance
        between those vectors. This works for Scipy's metrics, but is less
        efficient than passing the metric name as a string.

        Distance matrices are not supported.

    p : float, default=2
        Parameter for the Minkowski metric from
        sklearn.metrics.pairwise.pairwise_distances. When p = 1, this is
        equivalent to using manhattan_distance (l1), and euclidean_distance
        (l2) for p = 2. For arbitrary p, minkowski_distance (l_p) is used.
        This parameter is expected to be positive.

    metric_params : dict, default=None
        Additional keyword arguments for the metric function.

    n_jobs : int, default=None
        The number of parallel jobs to run for neighbors search.
        If ``-1``, then the number of jobs is set to the number of CPU cores.

    Attributes
    ----------
    effective_metric_ : str or callable
        The distance metric used. It will be same as the `metric` parameter
        or a synonym of it, e.g. 'euclidean' if the `metric` parameter set to
        'minkowski' and `p` parameter set to 2.

    effective_metric_params_ : dict
        Additional keyword arguments for the metric function. For most metrics
        will be same with `metric_params` parameter, but may also contain the
        `p` parameter value if the `effective_metric_` attribute is set to
        'minkowski'.

    n_features_in_ : int
        Number of features seen during :term:`fit`.

    n_samples_fit_ : int
        Number of samples in the fitted data.
    """

    from ...regression.knn.knn import BallTree, KDTree

    def __init__(self,
                 mode: Literal["distance", "connectivity"]='distance',
                 n_neighbors: int=5,
                 algorithm: Union[Literal["auto", "ball_tree", "kd_tree", "brute"],
                    Callable, nn.Module]='auto',
                 leaf_size: int=30,
                 metric: Union[str, Callable, nn.Module]='minkowski',
                 p: float = 2,
                 metric_params: dict = None,
                 n_jobs: int = None,
                 device: Union[str, torch.device] = "cpu",
                 dtype: torch.dtype = torch.float,
                 *args,
                 **kwargs,
                 ):
        super().__init__()
        if metric_params is None:
            metric_params = {}
        metric_params["p"] = p
        from ....utils.utils import MLCluster
        self.metric = MLCluster()._create_metric(metric, metric_params).metric

        self.mode = mode
        self.n_neighbors = n_neighbors
        self.algorithm = algorithm
        self.leaf_size = leaf_size
        self._metric_name = metric
        self.p = p
        self.metric_params = metric_params
        self.n_jobs = n_jobs
        self.device = (torch.device(device)
                       if isinstance(device, str) else device)
        self.dtype = dtype
        self.args = args
        self.kwargs = kwargs

        # Fitted attributes
        self._fit_X: Optional[torch.Tensor] = None
        self._tree: Optional[Any] = None
        self._algorithm: Optional[str] = None
        self.effective_metric_: Any = metric
        self.effective_metric_params_: Dict = metric_params
        self.n_features_in_: Optional[int] = None
        self.n_samples_fit_: Optional[int] = None
        self.fit_status = False

    # ------------------------------------------------------------------
    def _resolve_algorithm(self, n_features: int, n_samples: int) -> str:
        alg = self.algorithm
        if callable(alg) or isinstance(alg, nn.Module):
            return "brute"
        if alg == "auto":
            return "brute"  # safe default; tree construction done in fit
        return alg

    # ------------------------------------------------------------------
    def fit(self, X: Any, y: Any = None, **kwargs) -> "KNeighborsTransformer":
        X_t = _to_tensor(X, self.dtype, self.device)
        if X_t.ndim == 1:
            X_t = X_t.unsqueeze(1)

        n_samples, n_features = X_t.shape
        self.n_features_in_ = n_features
        self.n_samples_fit_ = n_samples
        self._fit_X = X_t
        self._algorithm = self._resolve_algorithm(n_features, n_samples)

        if self._algorithm == "ball_tree":
            from ...regression.knn.knn import BallTree
            self._tree = BallTree(X_t, leaf_size=self.leaf_size,
                                  metric=self.metric,
                                  device=str(self.device), dtype=self.dtype)
        elif self._algorithm == "kd_tree":
            from ...regression.knn.knn import KDTree
            self._tree = KDTree(X_t, leaf_size=self.leaf_size,
                                metric=self.metric,
                                device=str(self.device), dtype=self.dtype)
        else:
            self._tree = None  # brute force

        self.fit_status = True
        return self

    # ------------------------------------------------------------------
    def _kneighbors(self, X_t: torch.Tensor,
                    n_neighbors: int) -> Tuple[torch.Tensor, torch.Tensor]:
        """Return (distances, indices) of shape (n, k)."""
        if self._tree is not None:
            dists, inds = self._tree.query(X_t, k=n_neighbors,
                                           return_distance=True)
        else:
            # Brute force
            all_dists = self.metric(X_t, self._fit_X)  # (n_test, n_train)
            k = min(n_neighbors, all_dists.shape[1])
            dists, inds = torch.topk(all_dists, k=k, dim=1, largest=False)
        return dists.to(self.device), inds.long().to(self.device)

    # ------------------------------------------------------------------
    def transform(self, X: Any, **kwargs) -> torch.Tensor:
        """
        Return a (n_samples, n_samples_fit_) adjacency matrix.

        Each row i has non-zero entries at the k nearest training-sample
        indices.  Values are distances (mode='distance') or ones
        (mode='connectivity').
        """
        if not self.fit_status:
            raise RuntimeError("Call fit() before transform().")
        X_t = _to_tensor(X, self.dtype, self.device)
        if X_t.ndim == 1:
            X_t = X_t.unsqueeze(1)

        n_test = X_t.shape[0]
        n_train = self.n_samples_fit_

        # For mode='distance' sklearn adds 1 extra neighbor (self)
        k = self.n_neighbors + (1 if self.mode == "distance" else 0)
        k = min(k, n_train)

        dists, inds = self._kneighbors(X_t, k)

        # Build dense graph (n_test, n_train)
        graph = torch.zeros(n_test, n_train,
                            dtype=self.dtype, device=self.device)
        rows = torch.arange(n_test, device=self.device).unsqueeze(1).expand_as(inds)

        if self.mode == "distance":
            graph[rows, inds] = dists.to(self.dtype)
        else:  # connectivity
            graph[rows, inds] = 1.0

        return graph

    # ------------------------------------------------------------------
    def fit_transform(self, X: Any, y: Any = None, **kwargs) -> torch.Tensor:
        return self.fit(X, y, **kwargs).transform(X, **kwargs)

    # ------------------------------------------------------------------
    def forward(self, X: Any, **kwargs) -> torch.Tensor:
        if not self.fit_status:
            self.fit(X, **kwargs)
        return self.transform(X, **kwargs)

    # ------------------------------------------------------------------
    def predict(self, X: Any, **kwargs) -> torch.Tensor:
        return self.transform(X, **kwargs)

    # ------------------------------------------------------------------
    def score(self, X: Any, y: Any = None, **kwargs) -> float:
        return 0.0


# ---------------------------------------------------------------------------
# RadiusNeighborsTransformer
# ---------------------------------------------------------------------------

class RadiusNeighborsTransformer(MLTransform):
    """
    Transform X into a (weighted) graph of neighbors nearer than a radius.

    The transformed data is a sparse graph as returned by
    `radius_neighbors_graph`.

    Read more in the :ref:`User Guide <neighbors_transformer>`.

    .. versionadded:: 0.22

    Parameters
    ----------
    mode : {'distance', 'connectivity'}, default='distance'
        Type of returned matrix: 'connectivity' will return the connectivity
        matrix with ones and zeros, and 'distance' will return the distances
        between neighbors according to the given metric.

    radius : float, default=1.0
        Radius of neighborhood in the transformed sparse graph.

    algorithm : {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'
        Algorithm used to compute the nearest neighbors:

        - 'ball_tree' will use :class:`BallTree`
        - 'kd_tree' will use :class:`KDTree`
        - 'brute' will use a brute-force search.
        - 'auto' will attempt to decide the most appropriate algorithm
          based on the values passed to :meth:`fit` method.

        Note: fitting on sparse input will override the setting of
        this parameter, using brute force.

    leaf_size : int, default=30
        Leaf size passed to BallTree or KDTree.  This can affect the
        speed of the construction and query, as well as the memory
        required to store the tree.  The optimal value depends on the
        nature of the problem.

    metric : str or callable, default='minkowski'
        Metric to use for distance computation. Default is "minkowski", which
        results in the standard Euclidean distance when p = 2. See the
        documentation of `scipy.spatial.distance
        <https://docs.scipy.org/doc/scipy/reference/spatial.distance.html>`_ and
        the metrics listed in
        :class:`~sklearn.metrics.pairwise.distance_metrics` for valid metric
        values.

        If metric is a callable function, it takes two arrays representing 1D
        vectors as inputs and must return one value indicating the distance
        between those vectors. This works for Scipy's metrics, but is less
        efficient than passing the metric name as a string.

        Distance matrices are not supported.

    p : float, default=2
        Parameter for the Minkowski metric from
        sklearn.metrics.pairwise.pairwise_distances. When p = 1, this is
        equivalent to using manhattan_distance (l1), and euclidean_distance
        (l2) for p = 2. For arbitrary p, minkowski_distance (l_p) is used.
        This parameter is expected to be positive.

    metric_params : dict, default=None
        Additional keyword arguments for the metric function.

    n_jobs : int, default=None
        The number of parallel jobs to run for neighbors search.
        If ``-1``, then the number of jobs is set to the number of CPU cores.

    Attributes
    ----------
    effective_metric_ : str or callable
        The distance metric used. It will be same as the `metric` parameter
        or a synonym of it, e.g. 'euclidean' if the `metric` parameter set to
        'minkowski' and `p` parameter set to 2.

    effective_metric_params_ : dict
        Additional keyword arguments for the metric function. For most metrics
        will be same with `metric_params` parameter, but may also contain the
        `p` parameter value if the `effective_metric_` attribute is set to
        'minkowski'.

    n_features_in_ : int
        Number of features seen during :term:`fit`.

        .. versionadded:: 0.24

    n_samples_fit_ : int
        Number of samples in the fitted data.
    """

    from ...regression.knn.knn import BallTree, KDTree

    def __init__(self,
                 mode: Literal["distance", "connectivity"] = 'distance',
                 radius: float = 1.0,
                 algorithm: Union[Literal["auto", "ball_tree", "kd_tree", "brute"],
                 Callable, nn.Module] = 'auto',
                 leaf_size: int = 30,
                 metric: Union[str, Callable, nn.Module] = 'minkowski',
                 p: float = 2,
                 metric_params: dict = None,
                 n_jobs: int = None,
                 device: Union[str, torch.device] = "cpu",
                 dtype: torch.dtype = torch.float,
                 *args,
                 **kwargs,
                 ):
        super().__init__()
        if metric_params is None:
            metric_params = {}
        metric_params["p"] = p
        from ....utils.utils import MLCluster
        self.metric = MLCluster()._create_metric(metric, metric_params).metric

        self.mode = mode
        self.radius = radius
        self.algorithm = algorithm
        self.leaf_size = leaf_size
        self._metric_name = metric
        self.p = p
        self.metric_params = metric_params
        self.n_jobs = n_jobs
        self.device = (torch.device(device)
                       if isinstance(device, str) else device)
        self.dtype = dtype
        self.args = args
        self.kwargs = kwargs

        # Fitted attributes
        self._fit_X: Optional[torch.Tensor] = None
        self._tree: Optional[Any] = None
        self._algorithm: Optional[str] = None
        self.effective_metric_: Any = metric
        self.effective_metric_params_: Dict = metric_params
        self.n_features_in_: Optional[int] = None
        self.n_samples_fit_: Optional[int] = None
        self.fit_status = False

    # ------------------------------------------------------------------
    def fit(self, X: Any, y: Any = None,
            **kwargs) -> "RadiusNeighborsTransformer":
        X_t = _to_tensor(X, self.dtype, self.device)
        if X_t.ndim == 1:
            X_t = X_t.unsqueeze(1)

        n_samples, n_features = X_t.shape
        self.n_features_in_ = n_features
        self.n_samples_fit_ = n_samples
        self._fit_X = X_t

        alg = self.algorithm
        self._algorithm = "brute" if (alg == "auto" or callable(alg)
                                      or isinstance(alg, nn.Module)) else alg

        if self._algorithm == "ball_tree":
            from ...regression.knn.knn import BallTree
            self._tree = BallTree(X_t, leaf_size=self.leaf_size,
                                  metric=self.metric,
                                  device=str(self.device), dtype=self.dtype)
        elif self._algorithm == "kd_tree":
            from ...regression.knn.knn import KDTree
            self._tree = KDTree(X_t, leaf_size=self.leaf_size,
                                metric=self.metric,
                                device=str(self.device), dtype=self.dtype)
        else:
            self._tree = None

        self.fit_status = True
        return self

    # ------------------------------------------------------------------
    def _radius_neighbors(self, X_t: torch.Tensor
                          ) -> Tuple[List[torch.Tensor], List[torch.Tensor]]:
        """Return (distances_list, indices_list) for each query point."""
        all_dists = self.metric(X_t, self._fit_X)   # (n_test, n_train)
        mask = all_dists <= self.radius

        dists_list, inds_list = [], []
        for i in range(X_t.shape[0]):
            row = mask[i]
            d = all_dists[i][row]
            idx = row.nonzero(as_tuple=True)[0]
            dists_list.append(d)
            inds_list.append(idx)
        return dists_list, inds_list

    # ------------------------------------------------------------------
    def transform(self, X: Any, **kwargs) -> torch.Tensor:
        """
        Return a (n_samples, n_samples_fit_) adjacency matrix.

        Entry [i, j] is non-zero if sample j is within `radius` of query i.
        Values are distances (mode='distance') or ones (mode='connectivity').
        """
        if not self.fit_status:
            raise RuntimeError("Call fit() before transform().")
        X_t = _to_tensor(X, self.dtype, self.device)
        if X_t.ndim == 1:
            X_t = X_t.unsqueeze(1)

        n_test = X_t.shape[0]
        n_train = self.n_samples_fit_

        graph = torch.zeros(n_test, n_train, dtype=self.dtype, device=self.device)

        if self._tree is not None and hasattr(self._tree, "query_radius"):
            try:
                dists_list, inds_list = self._tree.query_radius(
                    X_t, r=self.radius, return_distance=True, sort_results=False)
            except Exception:
                dists_list, inds_list = self._radius_neighbors(X_t)
        else:
            dists_list, inds_list = self._radius_neighbors(X_t)

        for i, (d, idx) in enumerate(zip(dists_list, inds_list)):
            if self.mode == "distance":
                graph[i, idx] = d.to(self.dtype)
            else:
                graph[i, idx] = 1.0

        return graph

    # ------------------------------------------------------------------
    def fit_transform(self, X: Any, y: Any = None, **kwargs) -> torch.Tensor:
        return self.fit(X, y, **kwargs).transform(X, **kwargs)

    # ------------------------------------------------------------------
    def forward(self, X: Any, **kwargs) -> torch.Tensor:
        if not self.fit_status:
            self.fit(X, **kwargs)
        return self.transform(X, **kwargs)

    # ------------------------------------------------------------------
    def predict(self, X: Any, **kwargs) -> torch.Tensor:
        return self.transform(X, **kwargs)

    # ------------------------------------------------------------------
    def score(self, X: Any, y: Any = None, **kwargs) -> float:
        return 0.0


# ---------------------------------------------------------------------------
# RandomTreesEmbeddings
# ---------------------------------------------------------------------------

def _apply_tree(node: Dict, X: torch.Tensor
                ) -> Tuple[torch.Tensor, int]:
    """
    Traverse a fitted decision-tree structure for each sample in X.

    Returns
    -------
    leaf_ids : (n_samples,) LongTensor  — per-sample leaf index (0-based)
    n_leaves : int                      — total number of leaves
    """
    # First pass: assign a unique integer ID to every leaf node (DFS order)
    leaf_id_map: Dict[int, int] = {}

    def _assign(node: Dict, nxt: int) -> int:
        if node.get("leaf", False):
            leaf_id_map[id(node)] = nxt
            return nxt + 1
        nxt = _assign(node["left"], nxt)
        nxt = _assign(node["right"], nxt)
        return nxt

    n_leaves = _assign(node, 0)

    # Second pass: route each sample to its leaf
    def _route(x: torch.Tensor, nd: Dict) -> int:
        if nd.get("leaf", False):
            return int(leaf_id_map[id(nd)])
        feat_idx = int(nd["feature"]) if isinstance(nd["feature"], (torch.Tensor, np.integer)) else nd["feature"]
        thresh = nd["threshold"]
        if isinstance(thresh, torch.Tensor):
            thresh = thresh.item()
        if x[feat_idx].item() <= thresh:
            return _route(x, nd["left"])
        return _route(x, nd["right"])

    n = int(X.shape[0])
    leaf_ids = torch.zeros(n, dtype=torch.long, device=X.device)
    for i in range(n):
        leaf_ids[i] = int(_route(X[i], node))

    return leaf_ids, n_leaves


class RandomTreesEmbeddings(MLTransform):
    """
    An ensemble of totally random trees.

    An unsupervised transformation of a dataset to a high-dimensional
    sparse representation. A datapoint is coded according to which leaf of
    each tree it is sorted into. Using a one-hot encoding of the leaves,
    this leads to a binary coding with as many ones as there are trees in
    the forest.

    The dimensionality of the resulting representation is
    ``n_out <= n_estimators * max_leaf_nodes``. If ``max_leaf_nodes == None``,
    the number of leaf nodes is at most ``n_estimators * 2 ** max_depth``.

    For an example of applying Random Trees Embedding to non-linear
    classification, see
    :ref:`sphx_glr_auto_examples_ensemble_plot_random_forest_embedding.py`.

    Read more in the :ref:`User Guide <random_trees_embedding>`.

    Parameters
    ----------
    n_estimators : int, default=100
        Number of trees in the forest.

        .. versionchanged:: 0.22
           The default value of ``n_estimators`` changed from 10 to 100
           in 0.22.

    max_depth : int, default=5
        The maximum depth of each tree. If None, then nodes are expanded until
        all leaves are pure or until all leaves contain less than
        min_samples_split samples.

    min_samples_split : int or float, default=2
        The minimum number of samples required to split an internal node:

        - If int, then consider `min_samples_split` as the minimum number.
        - If float, then `min_samples_split` is a fraction and
          `ceil(min_samples_split * n_samples)` is the minimum
          number of samples for each split.

        .. versionchanged:: 0.18
           Added float values for fractions.

    min_samples_leaf : int or float, default=1
        The minimum number of samples required to be at a leaf node.
        A split point at any depth will only be considered if it leaves at
        least ``min_samples_leaf`` training samples in each of the left and
        right branches.  This may have the effect of smoothing the model,
        especially in regression.

        - If int, then consider `min_samples_leaf` as the minimum number.
        - If float, then `min_samples_leaf` is a fraction and
          `ceil(min_samples_leaf * n_samples)` is the minimum
          number of samples for each node.

        .. versionchanged:: 0.18
           Added float values for fractions.

    min_weight_fraction_leaf : float, default=0.0
        The minimum weighted fraction of the sum total of weights (of all
        the input samples) required to be at a leaf node. Samples have
        equal weight when sample_weight is not provided.

    max_leaf_nodes : int, default=None
        Grow trees with ``max_leaf_nodes`` in best-first fashion.
        Best nodes are defined as relative reduction in impurity.
        If None then unlimited number of leaf nodes.

    min_impurity_decrease : float, default=0.0
        A node will be split if this split induces a decrease of the impurity
        greater than or equal to this value.

        The weighted impurity decrease equation is the following::

            N_t / N * (impurity - N_t_R / N_t * right_impurity
                                - N_t_L / N_t * left_impurity)

        where ``N`` is the total number of samples, ``N_t`` is the number of
        samples at the current node, ``N_t_L`` is the number of samples in the
        left child, and ``N_t_R`` is the number of samples in the right child.

        ``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,
        if ``sample_weight`` is passed.

        .. versionadded:: 0.19

    sparse_output : bool, default=True
        Whether or not to return a sparse CSR matrix, as default behavior,
        or to return a dense array compatible with dense pipeline operators.

    n_jobs : int, default=None
        The number of jobs to run in parallel. :meth:`fit`, :meth:`transform`,
        :meth:`decision_path` and :meth:`apply` are all parallelized over the
        trees. ``None`` means 1 unless in a :obj:`joblib.parallel_backend`
        context. ``-1`` means using all processors. See :term:`Glossary
        <n_jobs>` for more details.

    random_state : int, RandomState instance or None, default=None
        Controls the generation of the random `y` used to fit the trees
        and the draw of the splits for each feature at the trees' nodes.
        See :term:`Glossary <random_state>` for details.

    verbose : int, default=0
        Controls the verbosity when fitting and predicting.

    warm_start : bool, default=False
        When set to ``True``, reuse the solution of the previous call to fit
        and add more estimators to the ensemble, otherwise, just fit a whole
        new forest. See :term:`Glossary <warm_start>` and
        :ref:`tree_ensemble_warm_start` for details.

    Attributes
    ----------
    estimator_ : :class:`~sklearn.tree.ExtraTreeRegressor` instance
        The child estimator template used to create the collection of fitted
        sub-estimators.

        .. versionadded:: 1.2
           `base_estimator_` was renamed to `estimator_`.

    estimators_ : list of :class:`~sklearn.tree.ExtraTreeRegressor` instances
        The collection of fitted sub-estimators.

    feature_importances_ : ndarray of shape (n_features,)
        The feature importances (the higher, the more important the feature).

    n_features_in_ : int
        Number of features seen during :term:`fit`.

        .. versionadded:: 0.24

    n_outputs_ : int
        The number of outputs when ``fit`` is performed.

    one_hot_encoder_ : OneHotEncoder instance
        One-hot encoder used to create the sparse embedding.

    estimators_samples_ : list of arrays
        The subset of drawn samples (i.e., the in-bag samples) for each base
        estimator. Each subset is defined by an array of the indices selected.
    """
    def __init__(self,
                 n_estimators: int = 100,
                 max_depth: int = 5,
                 min_samples_split: Union[int, float] = 2,
                 min_samples_leaf: Union[int, float] = 1,
                 min_weight_fraction_leaf: float = 0.0,
                 max_leaf_nodes: int = None,
                 min_impurity_decrease: float = 0.0,
                 sparse_output: bool = True,
                 n_jobs: int = None,
                 random_state: Union[int, torch.Generator] = None,
                 verbose: int = 0,
                 warm_start: bool = False,
                 device: Union[str, torch.device] = "cpu",
                 dtype: torch.dtype = torch.float,
                 *args,
                 **kwargs,
                 ):
        super().__init__()
        self.n_estimators = n_estimators
        self.max_depth = max_depth
        self.min_samples_split = min_samples_split
        self.min_samples_leaf = min_samples_leaf
        self.min_weight_fraction_leaf = min_weight_fraction_leaf
        self.max_leaf_nodes = max_leaf_nodes
        self.min_impurity_decrease = min_impurity_decrease
        self.sparse_output = sparse_output
        self.n_jobs = n_jobs
        self.random_state = random_state
        self.verbose = verbose
        self.warm_start = warm_start
        self.device = (torch.device(device)
                       if isinstance(device, str) else device)
        self.dtype = dtype
        self.args = args
        self.kwargs = kwargs

        # Fitted attributes
        self.estimator_: Optional[Any] = None
        self.estimators_: List[Any] = []
        self.feature_importances_: Optional[torch.Tensor] = None
        self.n_features_in_: Optional[int] = None
        self.n_outputs_: int = 1
        self.one_hot_encoder_: Optional[Any] = None
        self.estimators_samples_: List[torch.Tensor] = []
        # leaf offsets so each tree's leaf IDs don't collide
        self._leaf_offsets: List[int] = []
        self._n_leaves_per_tree: List[int] = []
        self.fit_status = False

    # ------------------------------------------------------------------
    def _make_tree(self, seed: int) -> Any:
        from ...regression.tree_models.trees import ExtraTreeRegressor
        return ExtraTreeRegressor(
            max_depth=self.max_depth,
            min_samples_split=self.min_samples_split,
            min_samples_leaf=self.min_samples_leaf,
            min_weight_fraction_leaf=self.min_weight_fraction_leaf,
            max_leaf_nodes=self.max_leaf_nodes,
            min_impurity_decrease=self.min_impurity_decrease,
            random_state=seed,
            device=str(self.device),
            dtype=self.dtype,
        )

    # ------------------------------------------------------------------
    def fit(self, X: Any, y: Any = None, sample_weight: Any = None,
            **kwargs) -> "RandomTreesEmbeddings":
        X_t = _to_tensor(X, self.dtype, self.device)
        if X_t.ndim == 1:
            X_t = X_t.unsqueeze(1)

        n_samples, n_features = X_t.shape
        self.n_features_in_ = n_features
        self.n_outputs_ = 1

        gen = _make_generator(self.random_state, self.device)

        # warm_start: keep existing estimators and only add the difference
        start_idx = len(self.estimators_) if self.warm_start else 0
        if not self.warm_start:
            self.estimators_ = []
            self.estimators_samples_ = []
            self._leaf_offsets = []
            self._n_leaves_per_tree = []

        n_to_add = self.n_estimators - start_idx

        if self.verbose:
            print(f"[RandomTreesEmbeddings] Fitting {n_to_add} trees ...")

        for t_idx in range(n_to_add):
            seed = int(torch.randint(0, 2**31 - 1, (1,), generator=gen).item())
            tree = self._make_tree(seed)

            # Random y: standard normal labels force tree to split randomly
            y_rand = torch.randn(n_samples, 1, generator=gen,
                                 device=self.device, dtype=self.dtype)

            tree.fit(X_t, y_rand)

            self.estimators_.append(tree)
            # Record in-bag (all samples when no bootstrap)
            self.estimators_samples_.append(
                torch.arange(n_samples, device=self.device))

            if self.verbose and (t_idx + 1) % 10 == 0:
                print(f"  {t_idx + 1}/{n_to_add} trees done")

        # Pre-compute leaf offsets (needed for one-hot encoding offset)
        total_offset = (sum(self._n_leaves_per_tree)
                        if self._n_leaves_per_tree else 0)
        for tree in self.estimators_[start_idx:]:
            if not tree.is_fit:
                self._leaf_offsets.append(total_offset)
                self._n_leaves_per_tree.append(1)
                total_offset += 1
                continue
            # Dry-run on first sample to count leaves
            _, n_lv = _apply_tree(tree.tree_structure, X_t[:1])
            self._leaf_offsets.append(total_offset)
            self._n_leaves_per_tree.append(n_lv)
            total_offset += n_lv

        # Feature importances: mean across trees
        fi_list = []
        for tree in self.estimators_:
            if hasattr(tree, "feature_importances_"):
                fi = tree.feature_importances_
                if isinstance(fi, torch.Tensor):
                    fi_list.append(fi)
        if fi_list:
            self.feature_importances_ = torch.stack(fi_list).mean(dim=0)
        else:
            self.feature_importances_ = torch.zeros(
                n_features, device=self.device, dtype=self.dtype)

        self.estimator_ = self._make_tree(0)  # template (unfitted)
        self.fit_status = True
        return self

    # ------------------------------------------------------------------
    def apply(self, X: Any) -> torch.Tensor:
        """
        Return leaf indices for X across all trees.

        Returns
        -------
        X_leaves : (n_samples, n_estimators) LongTensor
        """
        if not self.fit_status:
            raise RuntimeError("Call fit() before apply().")
        X_t = _to_tensor(X, self.dtype, self.device)
        if X_t.ndim == 1:
            X_t = X_t.unsqueeze(1)

        n_samples = X_t.shape[0]
        X_leaves = torch.zeros(n_samples, len(self.estimators_),
                               dtype=torch.long, device=self.device)
        for t_idx, tree in enumerate(self.estimators_):
            if not tree.is_fit:
                continue
            leaf_ids, _ = _apply_tree(tree.tree_structure, X_t)
            X_leaves[:, t_idx] = leaf_ids

        return X_leaves

    # ------------------------------------------------------------------
    def transform(self, X: Any, **kwargs) -> torch.Tensor:
        """
        Return a (n_samples, n_leaves_total) one-hot encoded embedding.

        Each sample maps to the leaf it falls into per tree.
        If ``sparse_output=True``, returns a sparse tensor.
        """
        if not self.fit_status:
            raise RuntimeError("Call fit() before transform().")
        X_t = _to_tensor(X, self.dtype, self.device)
        if X_t.ndim == 1:
            X_t = X_t.unsqueeze(1)

        n_samples = X_t.shape[0]
        n_total_leaves = sum(self._n_leaves_per_tree)

        out = torch.zeros(n_samples, n_total_leaves,
                          dtype=self.dtype, device=self.device)

        for t_idx, tree in enumerate(self.estimators_):
            if not tree.is_fit:
                continue
            leaf_ids, _ = _apply_tree(tree.tree_structure, X_t)
            offset = int(self._leaf_offsets[t_idx])
            rows = torch.arange(int(n_samples), device=self.device, dtype=torch.long)
            out[rows, (leaf_ids + offset).long()] = 1.0

        if self.sparse_output:
            return out.to_sparse()
        return out

    # ------------------------------------------------------------------
    def fit_transform(self, X: Any, y: Any = None,
                      sample_weight: Any = None, **kwargs) -> torch.Tensor:
        return self.fit(X, y, sample_weight, **kwargs).transform(X, **kwargs)

    # ------------------------------------------------------------------
    def forward(self, X: Any, **kwargs) -> torch.Tensor:
        if not self.fit_status:
            self.fit(X, **kwargs)
        return self.transform(X, **kwargs)

    # ------------------------------------------------------------------
    def predict(self, X: Any, **kwargs) -> torch.Tensor:
        return self.transform(X, **kwargs)

    # ------------------------------------------------------------------
    def score(self, X: Any, y: Any = None, **kwargs) -> float:
        return 0.0


# ---------------------------------------------------------------------------
# FeatureUnion
# ---------------------------------------------------------------------------

class FeatureUnion(MLTransform):
    """
    Concatenates results of multiple transformer objects.

    This estimator applies a list of transformer objects in parallel to the
    input data, then concatenates the results. This is useful to combine
    several feature extraction mechanisms into a single transformer.

    Parameters of the transformers may be set using its name and the parameter
    name separated by a '__'. A transformer may be replaced entirely by
    setting the parameter with its name to another transformer, removed by
    setting to 'drop' or disabled by setting to 'passthrough' (features are
    passed without transformation).

    Read more in the :ref:`User Guide <feature_union>`.

    .. versionadded:: 0.13

    Parameters
    ----------
    transformer_list : list of (str, transformer) tuples
        List of transformer objects to be applied to the data. The first
        half of each tuple is the name of the transformer. The transformer can
        be 'drop' for it to be ignored or can be 'passthrough' for features to
        be passed unchanged.

        .. versionadded:: 1.1
           Added the option `"passthrough"`.

        .. versionchanged:: 0.22
           Deprecated `None` as a transformer in favor of 'drop'.

    n_jobs : int, default=None
        Number of jobs to run in parallel.
        ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
        ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
        for more details.

        .. versionchanged:: v0.20
           `n_jobs` default changed from 1 to None

    transformer_weights : dict, default=None
        Multiplicative weights for features per transformer.
        Keys are transformer names, values the weights.
        Raises ValueError if key not present in ``transformer_list``.

    verbose : bool, default=False
        If True, the time elapsed while fitting each transformer will be
        printed as it is completed.

    verbose_feature_names_out : bool, default=True
        If True, :meth:`get_feature_names_out` will prefix all feature names
        with the name of the transformer that generated that feature.
        If False, :meth:`get_feature_names_out` will not prefix any feature
        names and will error if feature names are not unique.

        .. versionadded:: 1.5

    Attributes
    ----------
    named_transformers : :class:`~sklearn.utils.Bunch`
        Dictionary-like object, with the following attributes.
        Read-only attribute to access any transformer parameter by user
        given name. Keys are transformer names and values are
        transformer parameters.

        .. versionadded:: 1.2

    n_features_in_ : int
        Number of features seen during :term:`fit`. Only defined if the
        underlying first transformer in `transformer_list` exposes such an
        attribute when fit.
    """
    def __init__(self,
                 transformers: Union[List[Union[list, tuple]],
                     Tuple[List[Union[list, tuple]]],
                     torch.Tensor,
                     None] = None,
                 n_jobs: int = None,
                 transformer_weights: dict = None,
                 verbose: bool = False,
                 verbose_feature_names_out: Union[bool, str, Callable[[str, str], str]] = True,
                 device: Union[str, torch.device] = "cpu",
                 dtype: torch.dtype = torch.float,
                 *args,
                 **kwargs,
                 ):
        super().__init__()
        self.transformers = list(transformers) if transformers is not None else []
        self.n_jobs = n_jobs
        self.transformer_weights = transformer_weights or {}
        self.verbose = verbose
        self.verbose_feature_names_out = verbose_feature_names_out
        self.device = (torch.device(device)
                       if isinstance(device, str) else device)
        self.dtype = dtype
        self.args = args
        self.kwargs = kwargs

        # Validate transformer_weights keys
        t_names = {entry[0] for entry in self.transformers}
        for k in self.transformer_weights:
            if k not in t_names:
                raise ValueError(
                    f"transformer_weights key {k!r} not found in transformer_list."
                )

        # Fitted attributes
        self.named_transformers: Dict[str, Any] = {}
        self.n_features_in_: Optional[int] = None
        self.fit_status = False

    # ------------------------------------------------------------------
    def fit(self, X: Any, y: Any = None, **kwargs) -> "FeatureUnion":
        X_t = _to_tensor(X, self.dtype, self.device)
        if X_t.ndim == 1:
            X_t = X_t.unsqueeze(1)
        self.n_features_in_ = X_t.shape[1]

        for entry in self.transformers:
            t_name, t = entry[0], entry[1]
            if t in ("drop", "passthrough", None):
                self.named_transformers[t_name] = t
                continue
            t0 = time.time() if self.verbose else None
            t.fit(X_t, y)
            self.named_transformers[t_name] = t
            if self.verbose:
                print(f"[FeatureUnion] Fitting {t_name!r} done in "
                      f"{time.time() - t0:.3f}s")

        self.fit_status = True
        return self

    # ------------------------------------------------------------------
    def transform(self, X: Any, **kwargs) -> torch.Tensor:
        if not self.fit_status:
            raise RuntimeError("Call fit() before transform().")
        X_t = _to_tensor(X, self.dtype, self.device)
        if X_t.ndim == 1:
            X_t = X_t.unsqueeze(1)

        parts: List[torch.Tensor] = []
        for entry in self.transformers:
            t_name, t = entry[0], entry[1]
            if t is None or t == "drop":
                continue
            if t == "passthrough":
                out = X_t
            else:
                out = t.transform(X_t)
                if isinstance(out, torch.Tensor) and out.is_sparse:
                    out = out.to_dense()
            out = out.to(dtype=self.dtype, device=self.device)
            if out.ndim == 1:
                out = out.unsqueeze(1)
            w = self.transformer_weights.get(t_name)
            if w is not None:
                out = out * w
            parts.append(out)

        if not parts:
            return torch.zeros(X_t.shape[0], 0,
                               dtype=self.dtype, device=self.device)
        return torch.cat(parts, dim=1)

    # ------------------------------------------------------------------
    def fit_transform(self, X: Any, y: Any = None, **kwargs) -> torch.Tensor:
        return self.fit(X, y, **kwargs).transform(X, **kwargs)

    # ------------------------------------------------------------------
    def get_feature_names_out(
        self, input_features: Optional[List[str]] = None
    ) -> List[str]:
        if not self.fit_status:
            raise RuntimeError("Call fit() before get_feature_names_out().")
        vfno = self.verbose_feature_names_out
        all_names: List[str] = []

        for entry in self.transformers:
            t_name, t = entry[0], entry[1]
            if t is None or t == "drop":
                continue
            if t == "passthrough":
                sub = (input_features if input_features
                       else [f"x{i}" for i in range(self.n_features_in_)])
            elif hasattr(t, "get_feature_names_out"):
                sub = list(t.get_feature_names_out())
            else:
                sub = [f"{t_name}_feat{i}" for i in range(
                    getattr(t, "n_output_features_", 1))]

            for fn in sub:
                if vfno is True:
                    all_names.append(f"{t_name}__{fn}")
                elif vfno is False:
                    all_names.append(fn)
                elif isinstance(vfno, str):
                    all_names.append(
                        vfno.format(transformer_name=t_name, feature_name=fn))
                elif callable(vfno):
                    all_names.append(vfno(t_name, fn))
                else:
                    all_names.append(fn)

        # Check uniqueness when verbose_feature_names_out=False
        if vfno is False and len(all_names) != len(set(all_names)):
            raise ValueError(
                "Feature names are not unique. Set "
                "verbose_feature_names_out=True to prefix feature names."
            )
        return all_names

    # ------------------------------------------------------------------
    def forward(self, X: Any, **kwargs) -> torch.Tensor:
        if not self.fit_status:
            self.fit(X, **kwargs)
        return self.transform(X, **kwargs)

    # ------------------------------------------------------------------
    def predict(self, X: Any, **kwargs) -> torch.Tensor:
        return self.transform(X, **kwargs)

    # ------------------------------------------------------------------
    def score(self, X: Any, y: Any = None, **kwargs) -> float:
        return 0.0
